<?php
require_once 'User.php'; // Include the parent class definition

class Admin extends User {
    private $adminId;

    public function __construct($firstName= null, $lastName= null, $email= null, $password= null, $adminId = null) {
        parent::__construct($firstName, $lastName, $email, $password);
        $this->adminId = $adminId;
    }
    

    public function getAdminId() {
        return $this->adminId;
    }

    public function setAdminId($adminId) {
        $this->adminId = $adminId;
    }

    public function insertAdminDatabase($conn) {
        // Prepare the SQL statement
        $sql_insert_user = "INSERT INTO users (FirstName, LastName, Email, PasswordHash)
                            VALUES (?, ?, ?, ?)";
        $stmt = $conn->prepare($sql_insert_user);
        
        // Bind parameters
        $stmt->bind_param("ssss", $this->getFirstName(), $this->getLastName(), $this->getEmail(), $this->getPassword());

        // Execute the statement
        $stmt->execute();

        // Get the ID of the inserted user
        $user_id = $conn->insert_id;

        // Close the statement
        $stmt->close();

        // Insert admin into admins table
        $sql_insert_admin = "INSERT INTO admins (UserId)
                             VALUES (?)";
        $stmt = $conn->prepare($sql_insert_admin);
        $stmt->bind_param("i", $user_id);
        $stmt->execute();

        // Get the autogenerated adminId from the admins table
        $this->adminId = $conn->insert_id;

        // Close the statement
        $stmt->close();
    }
    
    
    public function obtainWhoWantBecomeTutor($conn) {
        $sql = "SELECT u.FirstName, u.LastName, bt.StudentId
                FROM becometutor_requests bt
                INNER JOIN students s ON bt.StudentId = s.StudentId
                INNER JOIN users u ON s.UserId = u.UserId
                WHERE bt.Status = 'Pending'";
        $result = mysqli_query($conn, $sql);
        if (!$result) {
            echo "Error fetching tutor requests: " . mysqli_error($conn);
            exit();
        }
        return $result;
    }
    
    
    
    
}
?>
